"use client";

import { ChangeEvent, FormEvent, useState } from "react";
import { Upload } from "lucide-react";
import { chambers } from "@/constants/chambers";
import { productRepository } from "@/services/product-repository";
import { ChamberCode, Product, ProductInput } from "@/types/product";

const blank: ProductInput = { name: "", code: "", tare: 0, chamber: "D1", imageUrl: "", searchTerms: [], category: "", notes: "" };
interface Props { product?: Product; onSave: (input: ProductInput) => Promise<void>; onCancel: () => void; onDelete?: () => Promise<void>; }
export function ProductForm({ product, onSave, onCancel, onDelete }: Props) {
  const [values, setValues] = useState<ProductInput>(product ? { name: product.name, code: product.code, tare: product.tare, chamber: product.chamber, imageUrl: product.imageUrl ?? "", searchTerms: product.searchTerms ?? [], category: product.category ?? "", notes: product.notes ?? "" } : blank);
  const [preview, setPreview] = useState(product?.imageUrl ?? ""); const [file, setFile] = useState<File>(); const [isSaving, setIsSaving] = useState(false); const [error, setError] = useState("");
  const set = <K extends keyof ProductInput>(key: K, value: ProductInput[K]) => setValues((current) => ({ ...current, [key]: value }));
  const selectPhoto = (event: ChangeEvent<HTMLInputElement>) => { const selected = event.target.files?.[0]; if (!selected) return; if (!selected.type.startsWith("image/") || selected.size > 5 * 1024 * 1024) { setError("Escolha uma imagem de até 5 MB."); return; } setError(""); setFile(selected); setPreview(URL.createObjectURL(selected)); };
  const submit = async (event: FormEvent) => { event.preventDefault(); setIsSaving(true); setError(""); try { let imageUrl = values.imageUrl; if (file) { const uploaded = await productRepository.uploadPhoto(file); if (product?.imageUrl && product.imageUrl !== uploaded) await productRepository.removePhoto(product.imageUrl); imageUrl = uploaded; } await onSave({ ...values, name: values.name.trim(), code: values.code.trim(), imageUrl: imageUrl || undefined, category: values.category?.trim() || null, notes: values.notes?.trim() || null, searchTerms: values.searchTerms?.map((term) => term.trim()).filter(Boolean) }); } catch (reason) { setError(reason instanceof Error ? reason.message : "Não foi possível salvar."); } finally { setIsSaving(false); } };
  return <form onSubmit={submit} className="mt-5 space-y-5 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-black">{product ? "Editar produto" : "Novo produto"}</h2>{error && <p className="rounded-xl bg-red-50 p-3 font-semibold text-red-700">{error}</p>}<label className="block font-bold">Nome<input required value={values.name} onChange={(event) => set("name", event.target.value)} className="field" /></label><div className="grid grid-cols-2 gap-4"><label className="block font-bold">Código<input required value={values.code} onChange={(event) => set("code", event.target.value)} className="field" /></label><label className="block font-bold">Tara (kg)<input min="0" step="0.001" type="number" value={values.tare || ""} onChange={(event) => set("tare", Number(event.target.value))} className="field" /></label></div><label className="block font-bold">Categoria<input value={values.category ?? ""} onChange={(event) => set("category", event.target.value)} placeholder="Ex.: Bovinos" className="field" /></label><label className="block font-bold">Câmara<select value={values.chamber} onChange={(event) => set("chamber", event.target.value as ChamberCode)} className="field">{chambers.map((chamber) => <option key={chamber.code} value={chamber.code}>{chamber.code} — {chamber.description}</option>)}</select></label><label className="block font-bold">Termos alternativos<input value={values.searchTerms?.join(", ") ?? ""} onChange={(event) => set("searchTerms", event.target.value.split(","))} placeholder="Ex.: bife patinho, patinho cubos" className="field" /></label><label className="block font-bold">Observações<textarea value={values.notes ?? ""} onChange={(event) => set("notes", event.target.value)} className="field min-h-24" /></label><label className="block font-bold">Foto<div className="mt-2 flex items-center gap-4">{preview && <img src={preview} alt="Prévia" className="size-20 rounded-xl object-cover" />}<span className="inline-flex min-h-14 cursor-pointer items-center gap-2 rounded-xl bg-slate-100 px-4 font-bold text-slate-700"><Upload className="size-5" />Escolher imagem<input type="file" accept="image/*" onChange={selectPhoto} className="sr-only" /></span></div></label><div className="flex flex-wrap gap-3"><button disabled={isSaving} className="min-h-14 rounded-xl bg-rose-700 px-6 text-lg font-black text-white disabled:opacity-60">{isSaving ? "Salvando..." : "Salvar produto"}</button><button type="button" onClick={onCancel} className="min-h-14 rounded-xl px-5 text-lg font-bold">Cancelar</button>{onDelete && <button type="button" onClick={() => void onDelete()} className="min-h-14 rounded-xl px-4 font-bold text-red-700">Excluir</button>}</div></form>;
}
